#!/usr/bin/env python3
"""
Cetana Labs — Master Registry Generator (BK-009 / RFC-LAB-000-002)

Renders the root README.md "Master Project Registry" table from the relational
JSON data layer (data/portfolio.json + data/users.json), resolving owner_id ->
user name and reading live Health from each project's STATUS.md.

The generated block is written between the marker comments:
    <!-- BEGIN:registry -->
    ... generated table ...
    <!-- END:registry -->

Everything outside the markers is preserved verbatim. Zero external dependencies.

Usage:
    python3 scripts/generate_registry.py            # rewrite README.md in place
    python3 scripts/generate_registry.py --check     # exit 1 if README is stale
    python3 scripts/generate_registry.py --stdout     # print the table block only
"""

import sys
import re
import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = REPO_ROOT / "data"
PROJECTS_DIR = REPO_ROOT / "projects"
README = REPO_ROOT / "README.md"

BEGIN_MARKER = "<!-- BEGIN:registry -->"
END_MARKER = "<!-- END:registry -->"

ARCHETYPE_DISPLAY = {
    "control-plane": ("💻", "Control Plane"),
    "mini-app": ("💻", "Mini-App"),
    "research": ("📑", "Research"),
    "data-collection": ("📊", "Data Collection"),
    "verification": ("🔬", "Verification"),
}

DEV_ENV_DISPLAY = {
    "cloud": "☁️ Cloud",
    "local": "💻 Local",
}


def load_json(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))


def read_health(project: dict) -> str:
    """Read Current Health from the project's STATUS.md (live status source)."""
    status_file = PROJECTS_DIR / f"{project['id']}-{project['slug']}" / "STATUS.md"
    if not status_file.exists():
        return ""
    content = status_file.read_text(encoding="utf-8")
    m = re.search(r"\*\*Current Health\*\*\s*\|\s*([^|\n]+)", content)
    return m.group(1).strip() if m else ""


def is_onboarding(health: str) -> bool:
    return "onboarding" in health.lower() or "pending" in health.lower()


def build_registry_block(users: list, projects: list) -> str:
    users_by_id = {u["id"]: u for u in users}

    lines = [
        BEGIN_MARKER,
        "<!-- Generated by scripts/generate_registry.py from data/portfolio.json + data/users.json. Do not edit by hand. -->",
        "",
        "| ID | Project Name | Archetype | Health | Dev Env | Lead | Codebase / Reference | Executive Status (`STATUS.md`) |",
        "| :---: | :--- | :---: | :---: | :---: | :---: | :--- | :---: |",
    ]

    for p in sorted(projects, key=lambda x: x["id"]):
        pid = p["id"]
        dir_name = f"{pid}-{p['slug']}"
        owner = users_by_id.get(p["owner_id"], {})
        owner_name = owner.get("name", "— Unassigned")

        arch_icon, arch_name = ARCHETYPE_DISPLAY.get(p["archetype"], ("💻", p["archetype"]))
        health = read_health(p) or "🟢 On Track"

        # Dev Env: suppressed (—) while a project is still onboarding.
        dev_env = "—" if is_onboarding(health) else DEV_ENV_DISPLAY.get(p["dev_environment"], "—")

        # Project name cell with descriptor.
        descriptor = f" ({p['descriptor']})" if p.get("descriptor") else ""
        name_cell = f"**[{p['name']}](projects/{dir_name}/README.md)**{descriptor}"

        # Codebase / Reference cell.
        ref = p.get("reference_url")
        repo = p.get("repo_url")
        if repo and ref == repo:
            code_cell = f"[GitHub Repo]({repo})"
        elif ref and "github.com" in ref:
            code_cell = f"[GitHub Repo]({ref})"
        elif ref:
            # External reference (e.g. product/paper URL) — show a friendly label.
            label = re.sub(r"^https?://(www\.)?", "", ref).rstrip("/")
            code_cell = f"[{label}]({ref})"
        else:
            code_cell = "—"

        status_cell = f"[STATUS.md](projects/{dir_name}/STATUS.md)"

        lines.append(
            f"| **`{pid}`** | {name_cell} | {arch_icon} {arch_name} | "
            f"`{health}` | {dev_env} | {owner_name} | {code_cell} | {status_cell} |"
        )

    lines.append("")
    lines.append(END_MARKER)
    return "\n".join(lines)


def render(users, projects) -> str:
    return build_registry_block(users, projects)


def splice_into_readme(readme_text: str, block: str) -> str:
    pattern = re.compile(
        re.escape(BEGIN_MARKER) + r".*?" + re.escape(END_MARKER),
        re.DOTALL,
    )
    if not pattern.search(readme_text):
        raise SystemExit(
            "ERROR: registry markers not found in README.md. "
            f"Add a block delimited by '{BEGIN_MARKER}' and '{END_MARKER}'."
        )
    return pattern.sub(lambda _m: block, readme_text)


def main():
    argv = sys.argv[1:]
    users = load_json(DATA_DIR / "users.json")
    projects = load_json(DATA_DIR / "portfolio.json")
    block = render(users, projects)

    if "--stdout" in argv:
        print(block)
        return 0

    readme_text = README.read_text(encoding="utf-8")
    new_text = splice_into_readme(readme_text, block)

    if "--check" in argv:
        if new_text != readme_text:
            print("❌ README.md master registry is stale. Run: python3 scripts/generate_registry.py", file=sys.stderr)
            return 1
        print("✅ README.md master registry is in sync with data/.")
        return 0

    if new_text != readme_text:
        README.write_text(new_text, encoding="utf-8")
        print(f"✅ README.md master registry regenerated from data/ ({len(projects)} projects).")
    else:
        print("✅ README.md master registry already up to date.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
